// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/nikishin42/shortener/cmd/shortener/interfaces (interfaces: CreatorID)

// Package interfaces is a generated GoMock package.
package interfaces

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockCreatorID is a mock of CreatorID interface.
type MockCreatorID struct {
	ctrl     *gomock.Controller
	recorder *MockCreatorIDMockRecorder
}

// MockCreatorIDMockRecorder is the mock recorder for MockCreatorID.
type MockCreatorIDMockRecorder struct {
	mock *MockCreatorID
}

// NewMockCreatorID creates a new mock instance.
func NewMockCreatorID(ctrl *gomock.Controller) *MockCreatorID {
	mock := &MockCreatorID{ctrl: ctrl}
	mock.recorder = &MockCreatorIDMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCreatorID) EXPECT() *MockCreatorIDMockRecorder {
	return m.recorder
}

// CreateID mocks base method.
func (m *MockCreatorID) CreateID(arg0 []byte, arg1 string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateID", arg0, arg1)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateID indicates an expected call of CreateID.
func (mr *MockCreatorIDMockRecorder) CreateID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateID", reflect.TypeOf((*MockCreatorID)(nil).CreateID), arg0, arg1)
}
